name: JistExample
options:
  bundleIdPrefix: com.customerio.jist
  deploymentTarget:
    iOS: "16.2"
settings:
  base:
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
targets:
  JistExample:
    type: application
    platform: iOS
    sources:
      - path: JistExample
      - path: Shared
      - path: ../../Tests/JistTests/Fonts
    dependencies:
      - package: Jist
      - target: JistLiveActivity
    info:
      path: JistExample/Info.plist
      properties:
        NSSupportsLiveActivities: true
        UILaunchScreen: {}
        UIAppFonts:
          - AbrilFatface-Regular.ttf
          - DMSans-Regular.ttf
          - DMSans-Medium.ttf
          - DMSans-SemiBold.ttf
          - DMSans-Bold.ttf
  JistLiveActivity:
    type: app-extension
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.customerio.jist.JistExample.JistLiveActivity
    sources:
      - path: JistLiveActivity
      - path: Shared
    dependencies:
      - package: Jist
    info:
      path: JistLiveActivity/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
packages:
  Jist:
    path: ../
