const fs = require("fs");
const { execSync } = require("child_process");

function generateCssModule() {
  const css = fs.readFileSync("src/jist.css", "utf8");
  const escaped = css.replace(/`/g, "\\`").replace(/\$/g, "\\$");
  fs.writeFileSync("src/jist-css.ts", `export default \`${escaped}\`;\n`);
}

// The jist-core (Rust) wasm module is a build input — without it the compiled
// element cannot resolve ./wasm/jist_core.js and every consumer install breaks.
if (!fs.existsSync("src/wasm/jist_core.js")) {
  console.error(
    "src/wasm is missing — build the Rust core first: npm run build:wasm " +
    "(requires the Rust toolchain + wasm-bindgen; see core/build-all.sh)"
  );
  process.exit(1);
}

generateCssModule();
execSync("tsc", { stdio: "inherit" });

fs.copyFileSync("src/jist.css", "dist/jist.css");
fs.copyFileSync("../LICENSE", "dist/LICENSE");

// jist-core (Rust) wasm module — generated by `npm run build:wasm`, consumed
// at runtime by jist-element. Ship it inside dist/.
fs.cpSync("src/wasm", "dist/wasm", { recursive: true });

module.exports = { generateCssModule };
